server:
  port: 8085

game-frame:
  scan: com.simple.mardice
  game-id: 1
  enable-link-logic: true

#websocket:
#  url: https://localhost/speedBoot

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  application:
    name: mar
  main:
    allow-circular-references: true

dubbo:
  application:
    name: mar
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://nacos
    check: false
  scan:
    base-packages: com.simple.gameframe.service.impl
  consumer:
    check: false
    timeout: 60000
    retries: 0
  cloud:
    subscribed-services: game-service