server:
  port: 8083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  application:
    name: game-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/yzhtzee
    username: root
    password: 123456
  flyway:
    enabled: true # 开启
    clean-disabled: false # 禁止清理数据表
    table: flyway_schema_history # 版本控制信息表名，默认 flyway_schema_history
    out-of-order: false # 是否允许不按顺序迁移
    baseline-on-migrate: true  # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-version: 0 # 与 baseline-on-migrate: true 搭配使用，小于此版本的不执行
    locations: classpath:db/migration   #默认sql脚本路径为classpath:db/migration
  main:
    allow-circular-references: true

dubbo:
  application:
    name: game-service
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.simple.gameservice.service.impl
  registry:
    address: spring-cloud://nacos
    check: false
  consumer:
    timeout: 60000
    retries: 0
    check: false
  cloud:
    subscribed-services: speed-boot, mar

logging:
  level:
    com.simple.gameservice: trace
    org.springframework.messaging.simp: debug