dubbo:
  application:
    id: user-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://172.30.60.82
    check: false
  consumer:
    check: false
  cloud:
    subscribed-services: user-service

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.60.82:8848
  main:
    allow-circular-references: true

websocket:
  url: https://localhost/speedBoot