dubbo:
  application:
    id: user-service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://localhost
    check: false
  consumer:
    check: false
  cloud:
    subscribed-services: user-service

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848