server:
  port: 7081
  servlet:
    session:
      timeout: 10080

dubbo:
  application:
    name: web-application-dev
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
    check: false
  consumer:
    timeout: 60000
    retries: 0
    check: false
  cloud:
    subscribed-services: user-service-dev,game-service-dev

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false

websocket:
  speed-boot: http://localhost:7084/speedBoot
  mar: http://localhost:7085/speedBoot

avatar:
  path: /Users/wangwubei/IdeaProjects/game/img/avatar/
#测试