dubbo:
  application:
    name: web-application
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
    check: false
  consumer:
    timeout: 60000
    retries: 0
    check: false
#  cloud:
#    subscribed-services: user-service,game-service

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false

websocket:
  url: http://localhost:8084/speedBoot