server:
  port: 8084

spring:
  profiles:
    active: dev

#mybatis-plus:
  #config-location: classpath:mapper/*.xml
  #type-aliases-package: com.simple.speedbootdice.pojo
logging:
  level:
    com.simple.speedbootdice: trace
    org.springframework.messaging.simp: debug