game-frame:
  scan: com.simple.speedbootdice

#websocket:
#  url: https://localhost/speedBoot

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.60.82:8848
  application:
    name: speed-boot
  main:
    allow-circular-references: true

dubbo:
  application:
    id: speed-boot
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://172.30.60.82
    check: false
  consumer:
    check: false
  cloud:
    subscribed-services: speed-boot